services:
  - type: web
    name: discord-music-bot
    env: python
    plan: free
    buildCommand: chmod +x render_build.sh && ./render_build.sh
    startCommand: export PATH="$PWD/node/bin:$PATH" && python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: YOUTUBE_COOKIES
        sync: false
      - key: PORT
        value: 8080
